-- Proyecto Lenguaje de Base de Datos
-- Grupo 4
-- Modelo Funional para La farmacia La Leona


--Creacion de Tablas

CREATE TABLE FIDE_CLIENTES_TB (
    CLIENTES_ID_CLIENTE_PK INT PRIMARY KEY,
    NOMBRE VARCHAR2(100),
    CORREO VARCHAR2(100),
    TELEFONO VARCHAR2(20),
    DIRECCION VARCHAR2(255),
    FECHA_NACIMIENTO DATE
);

CREATE TABLE FIDE_EMPLEADOS_TB (
    EMPLEADOS_ID_EMPLEADO_PK INT PRIMARY KEY,
    NOMBRE VARCHAR2(100),
    CORREO VARCHAR2(100),
    TELEFONO VARCHAR2(20),
    ROL VARCHAR2(50)
);

CREATE TABLE FIDE_PROVEEDORES_TB (
    PROVEEDORES_ID_PROVEEDOR_PK INT PRIMARY KEY,
    NOMBRE VARCHAR2(100),
    TELEFONO VARCHAR2(20),
    DIRECCION VARCHAR2(255)
);

CREATE TABLE FIDE_CATEGORIAS_PRODUCTO_TB (
    CATEGORIAS_PRODUCTO_ID_CATEGORIA_PK INT PRIMARY KEY,
    NOMBRE_CATEGORIA VARCHAR2(100)
);

CREATE TABLE FIDE_PRODUCTOS_TB (
    PRODUCTOS_ID_PRODUCTO_PK INT PRIMARY KEY,
    NOMBRE VARCHAR2(100),
    DESCRIPCION VARCHAR2(255),
    PRECIO DECIMAL(10, 2),
    STOCK INT,
    ID_PROVEEDOR INT,
    ID_CATEGORIA INT,
    FOREIGN KEY (ID_PROVEEDOR) REFERENCES FIDE_PROVEEDORES_TB(PROVEEDORES_ID_PROVEEDOR_PK),
    FOREIGN KEY (ID_CATEGORIA) REFERENCES FIDE_CATEGORIAS_PRODUCTO_TB(CATEGORIAS_PRODUCTO_ID_CATEGORIA_PK)
);

CREATE TABLE FIDE_PEDIDOS_TB (
    PEDIDOS_ID_PEDIDO_PK INT PRIMARY KEY,
    ID_CLIENTE INT,
    FECHA_PEDIDO DATE,
    TOTAL DECIMAL(10,2),
    FOREIGN KEY (ID_CLIENTE) REFERENCES FIDE_CLIENTES_TB(CLIENTES_ID_CLIENTE_PK)
);

CREATE TABLE FIDE_DETALLE_PEDIDO_TB (
    DETALLE_PEDIDO_ID_DETALLE_PK INT PRIMARY KEY,
    ID_PEDIDO INT,
    ID_PRODUCTO INT,
    CANTIDAD INT,
    SUBTOTAL DECIMAL(10, 2),
    FOREIGN KEY (ID_PEDIDO) REFERENCES FIDE_PEDIDOS_TB(PEDIDOS_ID_PEDIDO_PK),
    FOREIGN KEY (ID_PRODUCTO) REFERENCES FIDE_PRODUCTOS_TB(PRODUCTOS_ID_PRODUCTO_PK)
);

CREATE TABLE FIDE_CITAS_TB (
    CITAS_ID_CITA_PK INT PRIMARY KEY,
    ID_CLIENTE INT,
    ID_EMPLEADO INT,
    FECHA DATE,
    HORA VARCHAR2(10),
    MOTIVO VARCHAR2(255),
    FOREIGN KEY (ID_CLIENTE) REFERENCES FIDE_CLIENTES_TB(CLIENTES_ID_CLIENTE_PK),
    FOREIGN KEY (ID_EMPLEADO) REFERENCES FIDE_EMPLEADOS_TB(EMPLEADOS_ID_EMPLEADO_PK)
);

CREATE TABLE FIDE_HISTORIAL_COMPRAS_TB (
    HISTORIAL_COMPRAS_ID_HISTORIAL_PK INT PRIMARY KEY,
    ID_CLIENTE INT,
    ID_PRODUCTO INT,
    FECHA DATE,
    CANTIDAD INT,
    PRECIO_UNITARIO DECIMAL(10,2),
    FOREIGN KEY (ID_CLIENTE) REFERENCES FIDE_CLIENTES_TB(CLIENTES_ID_CLIENTE_PK),
    FOREIGN KEY (ID_PRODUCTO) REFERENCES FIDE_PRODUCTOS_TB(PRODUCTOS_ID_PRODUCTO_PK)
);

CREATE TABLE FIDE_FACTURAS_TB (
    FACTURAS_ID_FACTURA_PK INT PRIMARY KEY,
    ID_PEDIDO INT,
    ID_EMPLEADO INT,
    FECHA_EMISION DATE,
    MONTO_TOTAL DECIMAL(10, 2),
    FOREIGN KEY (ID_PEDIDO) REFERENCES FIDE_PEDIDOS_TB(PEDIDOS_ID_PEDIDO_PK),
    FOREIGN KEY (ID_EMPLEADO) REFERENCES FIDE_EMPLEADOS_TB(EMPLEADOS_ID_EMPLEADO_PK)
);

CREATE TABLE FIDE_COMENTARIOS_CLIENTES_TB (
    COMENTARIOS_CLIENTES_ID_COMENTARIO_PK INT PRIMARY KEY,
    ID_CLIENTE INT,
    COMENTARIO VARCHAR2(255),
    FECHA DATE,
    FOREIGN KEY (ID_CLIENTE) REFERENCES FIDE_CLIENTES_TB(CLIENTES_ID_CLIENTE_PK)
);

CREATE TABLE FIDE_USUARIOS_LOGIN_TB (
    USUARIOS_LOGIN_ID_USUARIO_PK INT PRIMARY KEY,
    USUARIO VARCHAR2(50),
    CONTRASENA VARCHAR2(100),
    ROL VARCHAR2(50)
);



-- PROCEDIMIENTOS INSERCION

-- CLIENTES
CREATE OR REPLACE PROCEDURE FIDE_CLIENTES_INSERTAR_SP (
    P_ID_CLIENTE IN NUMBER,
    P_NOMBRE IN VARCHAR2,
    P_CORREO IN VARCHAR2,
    P_TELEFONO IN VARCHAR2,
    P_DIRECCION IN VARCHAR2,
    P_FECHA_NACIMIENTO IN DATE
)
IS
BEGIN
    INSERT INTO FIDE_CLIENTES_TB VALUES (
        P_ID_CLIENTE, P_NOMBRE, P_CORREO, P_TELEFONO, P_DIRECCION, P_FECHA_NACIMIENTO
    );
END;


-- EMPLEADOS
CREATE OR REPLACE PROCEDURE FIDE_EMPLEADOS_INSERTAR_SP (
    P_ID_EMPLEADO IN NUMBER,
    P_NOMBRE IN VARCHAR2,
    P_CORREO IN VARCHAR2,
    P_TELEFONO IN VARCHAR2,
    P_ROL IN VARCHAR2
)
IS
BEGIN
    INSERT INTO FIDE_EMPLEADOS_TB VALUES (
        P_ID_EMPLEADO, P_NOMBRE, P_CORREO, P_TELEFONO, P_ROL
    );
END;


-- PROVEEDORES
CREATE OR REPLACE PROCEDURE FIDE_PROVEEDORES_INSERTAR_SP (
    P_ID_PROVEEDOR IN NUMBER,
    P_NOMBRE IN VARCHAR2,
    P_TELEFONO IN VARCHAR2,
    P_DIRECCION IN VARCHAR2
)
IS
BEGIN
    INSERT INTO FIDE_PROVEEDORES_TB VALUES (
        P_ID_PROVEEDOR, P_NOMBRE, P_TELEFONO, P_DIRECCION
    );
END;


-- CATEGORÍAS PRODUCTO
CREATE OR REPLACE PROCEDURE FIDE_CATEGORIAS_PRODUCTO_INSERTAR_SP (
    P_ID_CATEGORIA IN NUMBER,
    P_NOMBRE_CATEGORIA IN VARCHAR2
)
IS
BEGIN
    INSERT INTO FIDE_CATEGORIAS_PRODUCTO_TB VALUES (
        P_ID_CATEGORIA, P_NOMBRE_CATEGORIA
    );
END;


-- PRODUCTOS
CREATE OR REPLACE PROCEDURE FIDE_PRODUCTOS_INSERTAR_SP (
    P_ID_PRODUCTO IN NUMBER,
    P_NOMBRE IN VARCHAR2,
    P_DESCRIPCION IN VARCHAR2,
    P_PRECIO IN DECIMAL,
    P_STOCK IN NUMBER,
    P_ID_PROVEEDOR IN NUMBER,
    P_ID_CATEGORIA IN NUMBER
)
IS
BEGIN
    INSERT INTO FIDE_PRODUCTOS_TB VALUES (
        P_ID_PRODUCTO, P_NOMBRE, P_DESCRIPCION, P_PRECIO, P_STOCK, P_ID_PROVEEDOR, P_ID_CATEGORIA
    );
END;


-- PEDIDOS
CREATE OR REPLACE PROCEDURE FIDE_PEDIDOS_INSERTAR_SP (
    P_ID_PEDIDO IN NUMBER,
    P_ID_CLIENTE IN NUMBER,
    P_FECHA_PEDIDO IN DATE,
    P_TOTAL IN DECIMAL
)
IS
BEGIN
    INSERT INTO FIDE_PEDIDOS_TB VALUES (
        P_ID_PEDIDO, P_ID_CLIENTE, P_FECHA_PEDIDO, P_TOTAL
    );
END;


-- DETALLE PEDIDO
CREATE OR REPLACE PROCEDURE FIDE_DETALLE_PEDIDO_INSERTAR_SP (
    P_ID_DETALLE IN NUMBER,
    P_ID_PEDIDO IN NUMBER,
    P_ID_PRODUCTO IN NUMBER,
    P_CANTIDAD IN NUMBER,
    P_SUBTOTAL IN DECIMAL
)
IS
BEGIN
    INSERT INTO FIDE_DETALLE_PEDIDO_TB VALUES (
        P_ID_DETALLE, P_ID_PEDIDO, P_ID_PRODUCTO, P_CANTIDAD, P_SUBTOTAL
    );
END;


-- CITAS
CREATE OR REPLACE PROCEDURE FIDE_CITAS_INSERTAR_SP (
    P_ID_CITA IN NUMBER,
    P_ID_CLIENTE IN NUMBER,
    P_ID_EMPLEADO IN NUMBER,
    P_FECHA IN DATE,
    P_HORA IN VARCHAR2,
    P_MOTIVO IN VARCHAR2
)
IS
BEGIN
    INSERT INTO FIDE_CITAS_TB VALUES (
        P_ID_CITA, P_ID_CLIENTE, P_ID_EMPLEADO, P_FECHA, P_HORA, P_MOTIVO
    );
END;


-- HISTORIAL COMPRAS
CREATE OR REPLACE PROCEDURE FIDE_HISTORIAL_COMPRAS_INSERTAR_SP (
    P_ID_HISTORIAL IN NUMBER,
    P_ID_CLIENTE IN NUMBER,
    P_ID_PRODUCTO IN NUMBER,
    P_FECHA IN DATE,
    P_CANTIDAD IN NUMBER,
    P_PRECIO_UNITARIO IN DECIMAL
)
IS
BEGIN
    INSERT INTO FIDE_HISTORIAL_COMPRAS_TB VALUES (
        P_ID_HISTORIAL, P_ID_CLIENTE, P_ID_PRODUCTO, P_FECHA, P_CANTIDAD, P_PRECIO_UNITARIO
    );
END;


-- FACTURAS
CREATE OR REPLACE PROCEDURE FIDE_FACTURAS_INSERTAR_SP (
    P_ID_FACTURA IN NUMBER,
    P_ID_PEDIDO IN NUMBER,
    P_ID_EMPLEADO IN NUMBER,
    P_FECHA_EMISION IN DATE,
    P_MONTO_TOTAL IN DECIMAL
)
IS
BEGIN
    INSERT INTO FIDE_FACTURAS_TB VALUES (
        P_ID_FACTURA, P_ID_PEDIDO, P_ID_EMPLEADO, P_FECHA_EMISION, P_MONTO_TOTAL
    );
END;


-- COMENTARIOS CLIENTES
CREATE OR REPLACE PROCEDURE FIDE_COMENTARIOS_CLIENTES_INSERTAR_SP (
    P_ID_COMENTARIO IN NUMBER,
    P_ID_CLIENTE IN NUMBER,
    P_COMENTARIO IN VARCHAR2,
    P_FECHA IN DATE
)
IS
BEGIN
    INSERT INTO FIDE_COMENTARIOS_CLIENTES_TB VALUES (
        P_ID_COMENTARIO, P_ID_CLIENTE, P_COMENTARIO, P_FECHA
    );
END;


-- USUARIOS LOGIN
CREATE OR REPLACE PROCEDURE FIDE_USUARIOS_LOGIN_INSERTAR_SP (
    P_ID_USUARIO IN NUMBER,
    P_USUARIO IN VARCHAR2,
    P_CONTRASENA IN VARCHAR2,
    P_ROL IN VARCHAR2
)
IS
BEGIN
    INSERT INTO FIDE_USUARIOS_LOGIN_TB VALUES (
        P_ID_USUARIO, P_USUARIO, P_CONTRASENA, P_ROL
    );
END;


--PROCEDIMIENTOS ACTUALIZAR

-- CLIENTES
CREATE OR REPLACE PROCEDURE FIDE_CLIENTES_ACTUALIZAR_SP (
    P_ID_CLIENTE IN NUMBER,
    P_NOMBRE IN VARCHAR2,
    P_CORREO IN VARCHAR2,
    P_TELEFONO IN VARCHAR2,
    P_DIRECCION IN VARCHAR2,
    P_FECHA_NACIMIENTO IN DATE
)
IS
BEGIN
    UPDATE FIDE_CLIENTES_TB SET
        NOMBRE = P_NOMBRE,
        CORREO = P_CORREO,
        TELEFONO = P_TELEFONO,
        DIRECCION = P_DIRECCION,
        FECHA_NACIMIENTO = P_FECHA_NACIMIENTO
    WHERE CLIENTES_ID_CLIENTE_PK = P_ID_CLIENTE;
END;


-- EMPLEADOS
CREATE OR REPLACE PROCEDURE FIDE_EMPLEADOS_ACTUALIZAR_SP (
    P_ID_EMPLEADO IN NUMBER,
    P_NOMBRE IN VARCHAR2,
    P_CORREO IN VARCHAR2,
    P_TELEFONO IN VARCHAR2,
    P_ROL IN VARCHAR2
)
IS
BEGIN
    UPDATE FIDE_EMPLEADOS_TB SET
        NOMBRE = P_NOMBRE,
        CORREO = P_CORREO,
        TELEFONO = P_TELEFONO,
        ROL = P_ROL
    WHERE EMPLEADOS_ID_EMPLEADO_PK = P_ID_EMPLEADO;
END;


-- PROVEEDORES
CREATE OR REPLACE PROCEDURE FIDE_PROVEEDORES_ACTUALIZAR_SP (
    P_ID_PROVEEDOR IN NUMBER,
    P_NOMBRE IN VARCHAR2,
    P_TELEFONO IN VARCHAR2,
    P_DIRECCION IN VARCHAR2
)
IS
BEGIN
    UPDATE FIDE_PROVEEDORES_TB SET
        NOMBRE = P_NOMBRE,
        TELEFONO = P_TELEFONO,
        DIRECCION = P_DIRECCION
    WHERE PROVEEDORES_ID_PROVEEDOR_PK = P_ID_PROVEEDOR;
END;


-- CATEGORÍAS PRODUCTO
CREATE OR REPLACE PROCEDURE FIDE_CATEGORIAS_PRODUCTO_ACTUALIZAR_SP (
    P_ID_CATEGORIA IN NUMBER,
    P_NOMBRE_CATEGORIA IN VARCHAR2
)
IS
BEGIN
    UPDATE FIDE_CATEGORIAS_PRODUCTO_TB SET
        NOMBRE_CATEGORIA = P_NOMBRE_CATEGORIA
    WHERE CATEGORIAS_PRODUCTO_ID_CATEGORIA_PK = P_ID_CATEGORIA;
END;


-- PRODUCTOS
CREATE OR REPLACE PROCEDURE FIDE_PRODUCTOS_ACTUALIZAR_SP (
    P_ID_PRODUCTO IN NUMBER,
    P_NOMBRE IN VARCHAR2,
    P_DESCRIPCION IN VARCHAR2,
    P_PRECIO IN DECIMAL,
    P_STOCK IN NUMBER,
    P_ID_PROVEEDOR IN NUMBER,
    P_ID_CATEGORIA IN NUMBER
)
IS
BEGIN
    UPDATE FIDE_PRODUCTOS_TB SET
        NOMBRE = P_NOMBRE,
        DESCRIPCION = P_DESCRIPCION,
        PRECIO = P_PRECIO,
        STOCK = P_STOCK,
        ID_PROVEEDOR = P_ID_PROVEEDOR,
        ID_CATEGORIA = P_ID_CATEGORIA
    WHERE PRODUCTOS_ID_PRODUCTO_PK = P_ID_PRODUCTO;
END;


-- PEDIDOS
CREATE OR REPLACE PROCEDURE FIDE_PEDIDOS_ACTUALIZAR_SP (
    P_ID_PEDIDO IN NUMBER,
    P_ID_CLIENTE IN NUMBER,
    P_FECHA_PEDIDO IN DATE,
    P_TOTAL IN DECIMAL
)
IS
BEGIN
    UPDATE FIDE_PEDIDOS_TB SET
        ID_CLIENTE = P_ID_CLIENTE,
        FECHA_PEDIDO = P_FECHA_PEDIDO,
        TOTAL = P_TOTAL
    WHERE PEDIDOS_ID_PEDIDO_PK = P_ID_PEDIDO;
END;


-- DETALLE PEDIDO
CREATE OR REPLACE PROCEDURE FIDE_DETALLE_PEDIDO_ACTUALIZAR_SP (
    P_ID_DETALLE IN NUMBER,
    P_ID_PEDIDO IN NUMBER,
    P_ID_PRODUCTO IN NUMBER,
    P_CANTIDAD IN NUMBER,
    P_SUBTOTAL IN DECIMAL
)
IS
BEGIN
    UPDATE FIDE_DETALLE_PEDIDO_TB SET
        ID_PEDIDO = P_ID_PEDIDO,
        ID_PRODUCTO = P_ID_PRODUCTO,
        CANTIDAD = P_CANTIDAD,
        SUBTOTAL = P_SUBTOTAL
    WHERE DETALLE_PEDIDO_ID_DETALLE_PK = P_ID_DETALLE;
END;


-- CITAS
CREATE OR REPLACE PROCEDURE FIDE_CITAS_ACTUALIZAR_SP (
    P_ID_CITA IN NUMBER,
    P_ID_CLIENTE IN NUMBER,
    P_ID_EMPLEADO IN NUMBER,
    P_FECHA IN DATE,
    P_HORA IN VARCHAR2,
    P_MOTIVO IN VARCHAR2
)
IS
BEGIN
    UPDATE FIDE_CITAS_TB SET
        ID_CLIENTE = P_ID_CLIENTE,
        ID_EMPLEADO = P_ID_EMPLEADO,
        FECHA = P_FECHA,
        HORA = P_HORA,
        MOTIVO = P_MOTIVO
    WHERE CITAS_ID_CITA_PK = P_ID_CITA;
END;


-- HISTORIAL COMPRAS
CREATE OR REPLACE PROCEDURE FIDE_HISTORIAL_COMPRAS_ACTUALIZAR_SP (
    P_ID_HISTORIAL IN NUMBER,
    P_ID_CLIENTE IN NUMBER,
    P_ID_PRODUCTO IN NUMBER,
    P_FECHA IN DATE,
    P_CANTIDAD IN NUMBER,
    P_PRECIO_UNITARIO IN DECIMAL
)
IS
BEGIN
    UPDATE FIDE_HISTORIAL_COMPRAS_TB SET
        ID_CLIENTE = P_ID_CLIENTE,
        ID_PRODUCTO = P_ID_PRODUCTO,
        FECHA = P_FECHA,
        CANTIDAD = P_CANTIDAD,
        PRECIO_UNITARIO = P_PRECIO_UNITARIO
    WHERE HISTORIAL_COMPRAS_ID_HISTORIAL_PK = P_ID_HISTORIAL;
END;


-- FACTURAS
CREATE OR REPLACE PROCEDURE FIDE_FACTURAS_ACTUALIZAR_SP (
    P_ID_FACTURA IN NUMBER,
    P_ID_PEDIDO IN NUMBER,
    P_ID_EMPLEADO IN NUMBER,
    P_FECHA_EMISION IN DATE,
    P_MONTO_TOTAL IN DECIMAL
)
IS
BEGIN
    UPDATE FIDE_FACTURAS_TB SET
        ID_PEDIDO = P_ID_PEDIDO,
        ID_EMPLEADO = P_ID_EMPLEADO,
        FECHA_EMISION = P_FECHA_EMISION,
        MONTO_TOTAL = P_MONTO_TOTAL
    WHERE FACTURAS_ID_FACTURA_PK = P_ID_FACTURA;
END;


-- COMENTARIOS CLIENTES
CREATE OR REPLACE PROCEDURE FIDE_COMENTARIOS_CLIENTES_ACTUALIZAR_SP (
    P_ID_COMENTARIO IN NUMBER,
    P_ID_CLIENTE IN NUMBER,
    P_COMENTARIO IN VARCHAR2,
    P_FECHA IN DATE
)
IS
BEGIN
    UPDATE FIDE_COMENTARIOS_CLIENTES_TB SET
        ID_CLIENTE = P_ID_CLIENTE,
        COMENTARIO = P_COMENTARIO,
        FECHA = P_FECHA
    WHERE COMENTARIOS_CLIENTES_ID_COMENTARIO_PK = P_ID_COMENTARIO;
END;


-- USUARIOS LOGIN
CREATE OR REPLACE PROCEDURE FIDE_USUARIOS_LOGIN_ACTUALIZAR_SP (
    P_ID_USUARIO IN NUMBER,
    P_USUARIO IN VARCHAR2,
    P_CONTRASENA IN VARCHAR2,
    P_ROL IN VARCHAR2
)
IS
BEGIN
    UPDATE FIDE_USUARIOS_LOGIN_TB SET
        USUARIO = P_USUARIO,
        CONTRASENA = P_CONTRASENA,
        ROL = P_ROL
    WHERE USUARIOS_LOGIN_ID_USUARIO_PK = P_ID_USUARIO;
END;

--PROCEDIMIENTOS ELIMINAR

-- CLIENTES
CREATE OR REPLACE PROCEDURE FIDE_CLIENTES_ELIMINAR_SP (
    P_ID_CLIENTE IN NUMBER
)
IS
BEGIN
    DELETE FROM FIDE_CLIENTES_TB WHERE CLIENTES_ID_CLIENTE_PK = P_ID_CLIENTE;
END;


-- EMPLEADOS
CREATE OR REPLACE PROCEDURE FIDE_EMPLEADOS_ELIMINAR_SP (
    P_ID_EMPLEADO IN NUMBER
)
IS
BEGIN
    DELETE FROM FIDE_EMPLEADOS_TB WHERE EMPLEADOS_ID_EMPLEADO_PK = P_ID_EMPLEADO;
END;



-- PROVEEDORES
CREATE OR REPLACE PROCEDURE FIDE_PROVEEDORES_ELIMINAR_SP (
    P_ID_PROVEEDOR IN NUMBER
)
IS
BEGIN
    DELETE FROM FIDE_PROVEEDORES_TB WHERE PROVEEDORES_ID_PROVEEDOR_PK = P_ID_PROVEEDOR;
END;


-- CATEGORÍAS PRODUCTO
CREATE OR REPLACE PROCEDURE FIDE_CATEGORIAS_PRODUCTO_ELIMINAR_SP (
    P_ID_CATEGORIA IN NUMBER
)
IS
BEGIN
    DELETE FROM FIDE_CATEGORIAS_PRODUCTO_TB WHERE CATEGORIAS_PRODUCTO_ID_CATEGORIA_PK = P_ID_CATEGORIA;
END;


-- PRODUCTOS
CREATE OR REPLACE PROCEDURE FIDE_PRODUCTOS_ELIMINAR_SP (
    P_ID_PRODUCTO IN NUMBER
)
IS
BEGIN
    DELETE FROM FIDE_PRODUCTOS_TB WHERE PRODUCTOS_ID_PRODUCTO_PK = P_ID_PRODUCTO;
END;


-- PEDIDOS
CREATE OR REPLACE PROCEDURE FIDE_PEDIDOS_ELIMINAR_SP (
    P_ID_PEDIDO IN NUMBER
)
IS
BEGIN
    DELETE FROM FIDE_PEDIDOS_TB WHERE PEDIDOS_ID_PEDIDO_PK = P_ID_PEDIDO;
END;


-- DETALLE PEDIDO
CREATE OR REPLACE PROCEDURE FIDE_DETALLE_PEDIDO_ELIMINAR_SP (
    P_ID_DETALLE IN NUMBER
)
IS
BEGIN
    DELETE FROM FIDE_DETALLE_PEDIDO_TB WHERE DETALLE_PEDIDO_ID_DETALLE_PK = P_ID_DETALLE;
END;


-- CITAS
CREATE OR REPLACE PROCEDURE FIDE_CITAS_ELIMINAR_SP (
    P_ID_CITA IN NUMBER
)
IS
BEGIN
    DELETE FROM FIDE_CITAS_TB WHERE CITAS_ID_CITA_PK = P_ID_CITA;
END;


-- HISTORIAL COMPRAS
CREATE OR REPLACE PROCEDURE FIDE_HISTORIAL_COMPRAS_ELIMINAR_SP (
    P_ID_HISTORIAL IN NUMBER
)
IS
BEGIN
    DELETE FROM FIDE_HISTORIAL_COMPRAS_TB WHERE HISTORIAL_COMPRAS_ID_HISTORIAL_PK = P_ID_HISTORIAL;
END;


-- FACTURAS
CREATE OR REPLACE PROCEDURE FIDE_FACTURAS_ELIMINAR_SP (
    P_ID_FACTURA IN NUMBER
)
IS
BEGIN
    DELETE FROM FIDE_FACTURAS_TB WHERE FACTURAS_ID_FACTURA_PK = P_ID_FACTURA;
END;


-- COMENTARIOS CLIENTES
CREATE OR REPLACE PROCEDURE FIDE_COMENTARIOS_CLIENTES_ELIMINAR_SP (
    P_ID_COMENTARIO IN NUMBER
)
IS
BEGIN
    DELETE FROM FIDE_COMENTARIOS_CLIENTES_TB WHERE COMENTARIOS_CLIENTES_ID_COMENTARIO_PK = P_ID_COMENTARIO;
END;


-- USUARIOS LOGIN
CREATE OR REPLACE PROCEDURE FIDE_USUARIOS_LOGIN_ELIMINAR_SP (
    P_ID_USUARIO IN NUMBER
)
IS
BEGIN
    DELETE FROM FIDE_USUARIOS_LOGIN_TB WHERE USUARIOS_LOGIN_ID_USUARIO_PK = P_ID_USUARIO;
END;


-- VISTAS

-- 1. Vista de productos agotados
CREATE OR REPLACE VIEW FIDE_PRODUCTOS_AGOTADOS_V AS
SELECT PRODUCTOS_ID_PRODUCTO_PK AS ID_PRODUCTO, NOMBRE, STOCK
FROM FIDE_PRODUCTOS_TB
WHERE STOCK <= 0;

-- 2. Vista de pedidos por cliente
CREATE OR REPLACE VIEW FIDE_PEDIDOS_CLIENTE_V AS
SELECT C.NOMBRE AS CLIENTE, P.PEDIDOS_ID_PEDIDO_PK AS ID_PEDIDO, P.FECHA_PEDIDO, P.TOTAL
FROM FIDE_PEDIDOS_TB P
JOIN FIDE_CLIENTES_TB C ON P.ID_CLIENTE = C.CLIENTES_ID_CLIENTE_PK;

-- 3. Vista de historial de compras por producto
CREATE OR REPLACE VIEW FIDE_HISTORIAL_PRODUCTOS_V AS
SELECT H.HISTORIAL_COMPRAS_ID_HISTORIAL_PK AS ID_HISTORIAL, P.NOMBRE, H.CANTIDAD, H.FECHA
FROM FIDE_HISTORIAL_COMPRAS_TB H
JOIN FIDE_PRODUCTOS_TB P ON H.ID_PRODUCTO = P.PRODUCTOS_ID_PRODUCTO_PK;

-- 4. Vista de citas por fecha
CREATE OR REPLACE VIEW FIDE_CITAS_FECHA_V AS
SELECT C.CITAS_ID_CITA_PK AS ID_CITA, CL.NOMBRE AS CLIENTE, E.NOMBRE AS EMPLEADO, C.FECHA, C.HORA
FROM FIDE_CITAS_TB C
JOIN FIDE_CLIENTES_TB CL ON C.ID_CLIENTE = CL.CLIENTES_ID_CLIENTE_PK
JOIN FIDE_EMPLEADOS_TB E ON C.ID_EMPLEADO = E.EMPLEADOS_ID_EMPLEADO_PK;

-- 5. Vista de facturas emitidas
CREATE OR REPLACE VIEW FIDE_FACTURAS_EMITIDAS_V AS
SELECT F.FACTURAS_ID_FACTURA_PK AS ID_FACTURA, F.FECHA_EMISION, F.MONTO_TOTAL, E.NOMBRE AS EMPLEADO
FROM FIDE_FACTURAS_TB F
JOIN FIDE_EMPLEADOS_TB E ON F.ID_EMPLEADO = E.EMPLEADOS_ID_EMPLEADO_PK;

-- 6. Vista de comentarios recientes
CREATE OR REPLACE VIEW FIDE_COMENTARIOS_RECIENTES_V AS
SELECT C.COMENTARIOS_CLIENTES_ID_COMENTARIO_PK AS ID_COMENTARIO, CL.NOMBRE, C.COMENTARIO, C.FECHA
FROM FIDE_COMENTARIOS_CLIENTES_TB C
JOIN FIDE_CLIENTES_TB CL ON C.ID_CLIENTE = CL.CLIENTES_ID_CLIENTE_PK
WHERE C.FECHA >= SYSDATE - 30;


-- CURSORES 

-- 1. Productos con stock bajo
DECLARE
    CURSOR V_CURSOR_STOCK_BAJO IS
        SELECT NOMBRE, STOCK FROM FIDE_PRODUCTOS_TB WHERE STOCK < 10;
BEGIN
    FOR R IN V_CURSOR_STOCK_BAJO LOOP
        DBMS_OUTPUT.PUT_LINE('Producto: ' || R.NOMBRE || ' | Stock: ' || R.STOCK);
    END LOOP;
END;


-- 2. Pedidos mayores a ?50,000
DECLARE
    CURSOR V_CURSOR_PEDIDOS_ALTOS IS
        SELECT PEDIDOS_ID_PEDIDO_PK, TOTAL FROM FIDE_PEDIDOS_TB WHERE TOTAL > 50000;
BEGIN
    FOR R IN V_CURSOR_PEDIDOS_ALTOS LOOP
        DBMS_OUTPUT.PUT_LINE('Pedido: ' || R.PEDIDOS_ID_PEDIDO_PK || ' | Total: ' || R.TOTAL);
    END LOOP;
END;


-- 3. Comentarios recientes
DECLARE
    CURSOR V_CURSOR_COMENTARIOS IS
        SELECT COMENTARIO FROM FIDE_COMENTARIOS_CLIENTES_TB WHERE FECHA >= SYSDATE - 15;
BEGIN
    FOR R IN V_CURSOR_COMENTARIOS LOOP
        DBMS_OUTPUT.PUT_LINE('Comentario: ' || R.COMENTARIO);
    END LOOP;
END;


-- 4. Facturas emitidas hoy
DECLARE
    CURSOR V_CURSOR_FACTURAS_HOY IS
        SELECT FACTURAS_ID_FACTURA_PK, MONTO_TOTAL FROM FIDE_FACTURAS_TB WHERE FECHA_EMISION = TRUNC(SYSDATE);
BEGIN
    FOR R IN V_CURSOR_FACTURAS_HOY LOOP
        DBMS_OUTPUT.PUT_LINE('Factura: ' || R.FACTURAS_ID_FACTURA_PK || ' | Total: ' || R.MONTO_TOTAL);
    END LOOP;
END;


-- 5. Citas por empleado específico
DECLARE
    CURSOR V_CURSOR_CITAS_EMPLEADO IS
        SELECT C.CITAS_ID_CITA_PK, CL.NOMBRE
        FROM FIDE_CITAS_TB C
        JOIN FIDE_CLIENTES_TB CL ON C.ID_CLIENTE = CL.CLIENTES_ID_CLIENTE_PK
        WHERE ID_EMPLEADO = 1;
BEGIN
    FOR R IN V_CURSOR_CITAS_EMPLEADO LOOP
        DBMS_OUTPUT.PUT_LINE('Cita ID: ' || R.CITAS_ID_CITA_PK || ' | Cliente: ' || R.NOMBRE);
    END LOOP;
END;


-- 6. Historial de compras de un producto
DECLARE
    CURSOR V_CURSOR_COMPRAS_PRODUCTO IS
        SELECT ID_CLIENTE, CANTIDAD FROM FIDE_HISTORIAL_COMPRAS_TB WHERE ID_PRODUCTO = 1;
BEGIN
    FOR R IN V_CURSOR_COMPRAS_PRODUCTO LOOP
        DBMS_OUTPUT.PUT_LINE('Cliente: ' || R.ID_CLIENTE || ' | Cantidad: ' || R.CANTIDAD);
    END LOOP;
END;


-- 7. Proveedores registrados
DECLARE
    CURSOR V_CURSOR_PROVEEDORES IS
        SELECT NOMBRE FROM FIDE_PROVEEDORES_TB;
BEGIN
    FOR R IN V_CURSOR_PROVEEDORES LOOP
        DBMS_OUTPUT.PUT_LINE('Proveedor: ' || R.NOMBRE);
    END LOOP;
END;


-- 8. Usuarios y roles
DECLARE
    CURSOR V_CURSOR_USUARIOS IS
        SELECT USUARIO, ROL FROM FIDE_USUARIOS_LOGIN_TB;
BEGIN
    FOR R IN V_CURSOR_USUARIOS LOOP
        DBMS_OUTPUT.PUT_LINE('Usuario: ' || R.USUARIO || ' | Rol: ' || R.ROL);
    END LOOP;
END;

-- PAQUETE FARMACIA

--ESPECIFICACION

CREATE OR REPLACE PACKAGE FIDE_FARMACIA_PKG IS

  -- Procedimiento para mostrar productos con poco stock
  PROCEDURE MOSTRAR_PRODUCTOS_STOCK_BAJO;

  -- Procedimiento para listar citas del día
  PROCEDURE MOSTRAR_CITAS_HOY;

  -- Procedimiento para listar facturas emitidas por empleado
  PROCEDURE MOSTRAR_FACTURAS_EMPLEADO(P_ID_EMPLEADO NUMBER);

END FIDE_FARMACIA_PKG;

-- CUERPO

CREATE OR REPLACE PACKAGE BODY FIDE_FARMACIA_PKG IS

  PROCEDURE MOSTRAR_PRODUCTOS_STOCK_BAJO IS
  BEGIN
    FOR R IN (SELECT NOMBRE, STOCK FROM FIDE_PRODUCTOS_TB WHERE STOCK < 10) LOOP
      DBMS_OUTPUT.PUT_LINE('Producto: ' || R.NOMBRE || ' - Stock: ' || R.STOCK);
    END LOOP;
  END;

  PROCEDURE MOSTRAR_CITAS_HOY IS
  BEGIN
    FOR R IN (
      SELECT C.CITAS_ID_CITA_PK, CL.NOMBRE AS CLIENTE, E.NOMBRE AS EMPLEADO
      FROM FIDE_CITAS_TB C
      JOIN FIDE_CLIENTES_TB CL ON C.ID_CLIENTE = CL.CLIENTES_ID_CLIENTE_PK
      JOIN FIDE_EMPLEADOS_TB E ON C.ID_EMPLEADO = E.EMPLEADOS_ID_EMPLEADO_PK
      WHERE C.FECHA = TRUNC(SYSDATE)
    ) LOOP
      DBMS_OUTPUT.PUT_LINE('Cita ID: ' || R.CITAS_ID_CITA_PK || ' | Cliente: ' || R.CLIENTE || ' | Empleado: ' || R.EMPLEADO);
    END LOOP;
  END;

  PROCEDURE MOSTRAR_FACTURAS_EMPLEADO(P_ID_EMPLEADO NUMBER) IS
  BEGIN
    FOR R IN (
      SELECT FACTURAS_ID_FACTURA_PK, FECHA_EMISION, MONTO_TOTAL
      FROM FIDE_FACTURAS_TB
      WHERE ID_EMPLEADO = P_ID_EMPLEADO
    ) LOOP
      DBMS_OUTPUT.PUT_LINE('Factura ID: ' || R.FACTURAS_ID_FACTURA_PK || ' | Fecha: ' || R.FECHA_EMISION || ' | Monto: ' || R.MONTO_TOTAL);
    END LOOP;
  END;

END FIDE_FARMACIA_PKG;